project: 
  type: website
  output-dir: ../docs
  
#title: '<img src="images/icon.png" style="vertical-align: middle; width: 150px;">FromExceltoR'
title: 'FromExceltoR'
# author: 
website: 
  title: 'FromExceltoR'
  #favicon: '<img src="images/icon.png" style="vertical-align: middle; width: 150px;">'
  navbar:
    left: 
      - href: index.qmd
        text: 'Course Material'
      - href: about_heads.qmd
        text: 'About us'
        
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
    
      - href: Slideshow/FromExceltoR.pdf
        text: "Slides ğŸŒŸï¸"
      
      - section: "Presentations ğŸ‘©ğŸ½â€ğŸ«"
        contents:
          - href: Presentations/presentation1.qmd
            text: "Presentation 1: Introduction"
          - href: Presentations/presentation2.qmd
            text: "Presentation 2: Tidyverse"
          - href: Presentations/presentation3.qmd
            text: "Presentation 3: ggplot2"

      - href: Presentations/data.qmd
        text: "Data ğŸ—‚ï¸"
        
      - section: "Exercises ğŸ‹ğŸ½"
        contents:
          - href: Exercises/exercises1.qmd
            text: "Exercise 1: Introduction"
          - href: Exercises/exercises2.qmd
            text: "Exercise 2: Tidyverse"
          - href: Exercises/exercises3.qmd
            text: "Exercise 3: ggplot2"
          - href: Exercises/exercises4_PART1.qmd
            text: "Exercise 4, part 1: Statistics"
          - href: Exercises/exercises4_PART2.qmd
            text: "Exercise 4, part 2: Statistics"
          - href: Exercises/exercises5.qmd
            text: "Exercise 5: Data Exercise in R"
      
      - section: "Solutions ğŸ’ƒğŸ»"
        contents:
          - href: Solutions/solution_not_up.qmd # Solutions/exercises2_SOLUTIONS.qmd
            text: "Exercise 2 - Solution"
          - href: Solutions/solution_not_up.qmd # Solutions/exercises3_SOLUTIONS.qmd
            text: "Exercise 3 - Solution"
          - href: Solutions/solution_not_up.qmd # Solutions/solution4_PART1.qmd
            text: "Exercise 4, part 1 - Solution"
          - href: Solutions/solution_not_up.qmd # Solutions/solution4_PART2.qmd
            text: "Exercise 4, part 2 - Solution"
            
      - section: "Cheat Sheets ğŸ‘€"
        contents:
          - href: CheatSheet/quartoCheatSheet.pdf
            text: "Quarto"
          - href: CheatSheet/BaseRCheatSheet.pdf
            text: "Base R"
          - href: CheatSheet/TidyverseCheatSheet.pdf
            text: "Tidyverse"
          - href: CheatSheet/ggplotCheatSheet.pdf
            text: "ggplot2"
          

format:
  html:
    theme: flatly  # You can try different themes like cosmo, flatly, etc.
    # sidebar:
    #   collapse-level: 1
    toc: true # Add "On this page"
    toc-location: right
    
      
      
      
    
    
    
